name: PR has a valid Issue

on:
  pull_request_target:

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Testing job environment
        run: |
          echo "Hello From Production Envrionment."
