name: PR has a valid Issue

on:
  pull_request:
    types:
      - opened
      - assigned
      - edited
      - synchronize
      - labeled
      - enqueued
      - ready_for_review
      - review_requested
      - review_request_
  pull_request_target:
    types:
      - opened
      - assigned
      - edited
      - synchronize
      - labeled
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Testing job environment
        run: |
          echo "Hello From Production Envrionment."
