name: Check Issue Link in PR

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  check-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Issue Link
        uses: actions/github-script@v6
        with:
          script: |
            const pattern = /#(\d+)/;
            const issueLinkExists = pattern.test(github.event.pull_request.body);

            if (!issueLinkExists) {
              core.setFailed('Pull Request description does not contain an Issue link.');
            }
