name: Scheduled Job

on:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "The time is $(date)."