name: PR has a valid Issue

on:
  pull_request:
    types:
      - opened
      - assigned
      - edited
      - synchronize
      - labeled
  pull_request_target:
    types:
      - opened
      - assigned
      - edited
      - synchronize
      - labeled
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Testing job environment
        run: |
          echo "Hello From Production Envrionment."
