name: PR has a valid Issue

on:
  pull_request:
    [ assigned, edited, opened, reopened ]
  pull_request_target:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    runs-on: [ubuntu-latest]
    steps:
      - name: Testing job environment
        run: echo "Hello From Production Envrionment."
