name: PR has a valid Issue

on:
  pull_request:
    types:
      - opened
      - assigned
      - edited
      - synchronize
      - labeled
      - connected
      - enqueued
      - ready_for_review
      - review_requested
      - closed
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Testing job environment
        run: |
          echo "Hello From Production Envrionment."
          exit 1
